/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.tiernogalvan.proyecto.ui;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author vekto
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        hiber = new javax.swing.JButton();
        eclipse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        titulo.setText("DEMO ORM");

        hiber.setText("Hibernate");
        hiber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiberActionPerformed(evt);
            }
        });

        eclipse.setText("EclipseLink");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hiber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eclipse))
                    .addComponent(titulo))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(titulo)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiber)
                    .addComponent(eclipse))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hiberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiberActionPerformed

    public JButton getHiber() {
        return hiber;
    }

    public void setHiber(JButton hiber) {
        this.hiber = hiber;
    }

    public JButton getEclipse() {
        return eclipse;
    }

    public void setEclipse(JButton eclipse) {
        this.eclipse = eclipse;
    }

    public JLabel getjLabel1() {
        return titulo;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.titulo = jLabel1;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eclipse;
    private javax.swing.JButton hiber;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
